/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

import {
  glimpse1,
  glimpse2,
  glimpse3,
  glimpse4,
  glimpse5,
  glimpse6,
  glimpse7,
  glimpse8,
  glimpse9,
  thumbnail1,
  thumbnail2,
  thumbnail3,
  thumbnail4,
  thumbnail5,
  thumbnail6,
  thumbnail7,
  thumbnail8,
  thumbnail9,
} from "../../Assets/Images";

export const videos = [
  {
    _id: "f5exTHSBFvc",
    thumbnail: thumbnail1,
    glimpse: glimpse1,
    title: "Turnt Fashion Film",
    description:
      "Monochrome Dreams - a fashion film for the fourth chapter of the alternative fashion magazine TURNT.",
    creator: "Vivi & Tamas",
    category: "Fashion Film",
    views: "1.2M",
    label: "Must Watch",
    date: "Jan, 2020",
    showOnLanding: true,
  },
  {
    _id: "x87D2d0GNJc",
    thumbnail: thumbnail2,
    glimpse: glimpse2,
    title: "CHANEL Fashion Film",
    description:
      "New fashion film for Chanel featuring the brand's, 'Le Paris Russe De Chanel' Fine Jewelry collection. Shot in Paris at Le Grand Palais on RED Digital Cinema camera.",
    creator: "Vivi & Tamas",
    category: "Fashion Film",
    views: "2M",
    label: "Must Watch",
    date: "April, 2020",
    showOnLanding: false,
  },
  {
    _id: "uFgcSjVRJhE",
    thumbnail: thumbnail3,
    glimpse: glimpse3,
    title: "Jitesh Thakur Outfit Inspo",
    description: "Fashion Film featuring Jitesh Thakur. ",
    creator: "House of Creation",
    category: "Outfit Inspo",
    views: "80K",
    label: "",
    date: "Jan, 2021",
    showOnLanding: false,
  },
  {
    _id: "z5H9Ks--b-U",
    thumbnail: thumbnail4,
    glimpse: glimpse4,
    title: "DIOR Fashion Film 2018",
    description:
      "A Fine Uprising - a fashion film for MOJEH. Shot on RED Digital Cinema.",
    creator: "Vivi & Tamas",
    category: "Fashion Film",
    views: "75K",
    label: "Must Watch",
    date: "May, 2021",
  },
  {
    _id: "xsX7hQ-5tkA",
    thumbnail: thumbnail5,
    glimpse: glimpse5,
    title: "GUST Outfit Inspiration",
    description:
      "Want outfit inspiration this winter? When the temperature dips, it can be a challenge to pull together outfits that look fashionable, without freezing your buns off. But despite the chilly conditions outside, you can still have fun with fashion and look great every day.",
    creator: "Kevin Reyes",
    category: "Outfit Inspo",
    views: "1.2M",
    label: "",
    date: "Jan, 2019",
    showOnLanding: false,
  },
  {
    _id: "DvDpj-4FPog",
    thumbnail: thumbnail6,
    glimpse: glimpse6,
    title: "Zara Women Campaign",
    description:
      "Thank you Lexi Boling, Vitoria Cerreti, Kiki Willems, Leila Goldkhul, Luisiana Gonzales, Yoon Bae and Nora Attal.",
    creator: "Zara",
    views: "3M",
    label: "Featured",
    date: "Dec, 2020",
    showOnLanding: false,
    category: "Fashion Film",
  },
  {
    _id: "2VncgqDVk1E",
    showOnLanding: true,
    thumbnail: thumbnail7,
    glimpse: glimpse7,
    title: "CHANEL Fashion Film MOJE",
    description:
      "New fashion film for Chanel featuring the brand's, 'Le Paris Russe De Chanel' Fine Jewelry collection. Shot in Paris at Le Grand Palais on RED Digital Cinema camera.",
    creator: "Vivi & Tamas",
    category: "Fashion Film",
    views: "2M",
    label: "Must Watch",
    date: "April, 2020",
  },
  {
    _id: "CrJXwh7HkYU",
    showOnLanding: true,
    thumbnail: thumbnail8,
    glimpse: glimpse8,
    title: "CHANEL Fashion Film 2021",
    description:
      "New fashion film for LV featuring the brand's, 'Le Paris Russe De Chanel' Fine Jewelry collection. Shot in Paris at Le Grand Palais on RED Digital Cinema camera.",
    creator: "Vivi & Tamas",
    category: "Fashion Film",
    views: "1.2M",
    label: "Must Watch",
    date: "July, 2021",
  },
  {
    _id: "PYS3UZFPJWI",
    showOnLanding: false,
    thumbnail: thumbnail9,
    glimpse: glimpse9,
    title: "Kendall's Skincare Routine",
    description:
      "Watch model Kendall Jenner share her top beauty tips, from the moisturizing mask she makes at home to her multi-step bronzing process.",
    creator: "Vogue",
    category: "Skincare",
    views: "60K",
    label: "",
    date: "Jan, 2018",
  },
];
